### ISSUE TITLE
VS2015 compilation of tutorial failed: can not find libopenblas.dll.a  in CoMISo

### ISSUE THREAD

**Issue by liangbright** [libigl/CoMISo#1]
VS2015 compilation of tutorial failed: 
can not find libopenblas.dll.a in lib folder of https://github.com/libigl/CoMISo.git

Solved: 
(1)download the file from http://www.openblas.net/
(2)rename libopenblas.dll.a to libopenblas.dll.a.lib

**Comment by danielepanozzo** [comment]
Thanks for the report, could you please send a pull request with the fix?

**Comment by danielepanozzo** [comment]
Fixed.
