### ISSUE TITLE
Throw error in libopenblas.dll when in release mode

### ISSUE THREAD

**Issue by darkpursuer** [libigl/CoMISo#5]
Hi,

I found an interesting issue here. When I was using the `igl::copyleft::comiso::miq()` function, it would throw the following exception when the program was compiled in Release mode. But when I wanted to figure out how this happened in the Debug mode, the program was run successfully without any exception.  I don't know how this happened and there's no helpful information in the Release mode. I was using VS 2015.

![image](https://user-images.githubusercontent.com/7633152/39732821-72a832e8-523d-11e8-9956-5365afa39186.png)

I wondered that it could be because the debug mode may take more time than release mode? Or there might be an inevitable problem of memory management when used in Release mode in Windows.

**Comment by optexeon** [comment]
Same issue here, did you solve it?
